version: "3.9"
services:
  postgres14:
    image: postgres:14-alpine
    ports:
      - "5532:5432"
    environment:
      POSTGRES_PASSWORD: "123456"
      POSTGRES_DB: "benefits"
    volumes:
      - data-postgres:/var/lib/postgres/data
    restart: always
    networks:
      - macro
  model:
    build:
      context: ./
      dockerfile: ./model/Dockerfile
    ports:
      - "8001:8001"
    env_file: ./model/.env
    networks:
      - macro
    depends_on:
      - postgres14
    restart: always
volumes:
  data-postgres:
networks:
  macro:

